### ISSUE TITLE
Adding a License of this repository

### ISSUE THREAD

**Issue by ikasoumen** [gshigeto/ionic-environment-variables#12]
Hi, @gshigeto.
This information is what I wanted.
But I couldn't find the license information of this repository. 

Why don't you do adding a LICENSE file?
Can I use this information for my project?

**Comment by gshigeto** [comment]
@ikasoumen, thank you for your suggestion! I am glad that this is what you wanted.

I added a LICENSE and I give you permission to use this for your project.

Best!
