### ISSUE TITLE
Does not work with: ionic cordova run android --livereload

### ISSUE THREAD

**Issue by devfelipereis** [gshigeto/ionic-environment-variables#14]
Any way to make this work with **ionic cordova run android --livereload**?

I can get the dev configs but for production I can't. Any ideias?

Thank you!

**Comment by windhandel** [comment]
Maybe this? - https://stackoverflow.com/questions/46992418/dynamic-environment-variables-in-ionic-cannot-find-module

**Comment by Robinyo** [comment]
See:
- https://github.com/ionic-team/ionic-app-scripts/issues/1271
- https://github.com/ionic-team/ionic-app-scripts/blob/master/config/webpack.config.js

**Comment by LuisHCK** [comment]
Using the README's config and adding this script is working for me :D
package.json
`
  "android:dev": "APP_ENV=dev ionic cordova run android --emulator --livereload",
`

**Comment by devfelipereis** [comment]
I was busy and I could not try again... I'll run a new project and see what happens.. Thank you all.

**Comment by gshigeto** [comment]
If you still have a problem, feel free to open another issue! Thanks!
