### ISSUE TITLE
Error when set MY_ENV=prod

### ISSUE THREAD

**Issue by ThunderBirdsX3** [gshigeto/ionic-environment-variables#15]
I got an error `Module not found: Error: Can't resolve '@app/env'`.

**Comment by Robinyo** [comment]
See: https://robferguson.org/blog/2017/11/22/working-with-typescript-webpack-and-ionic-3/

**Comment by Robinyo** [comment]
See:

ionic-team/ionic-app-scripts#1271
https://github.com/ionic-team/ionic-app-scripts/blob/master/config/webpack.config.js

**Comment by kevikos** [comment]
Add the following to your tsconfig.json in **# **compilerOptions:****

"baseUrl": "./src",
"paths": {
  "@app/env": [
    "environments/environment"
  ]
}
