### ISSUE TITLE
How to run the app with custom environments?

### ISSUE THREAD

**Issue by diegofsza** [gshigeto/ionic-environment-variables#2]
Hi, thank you for this approach. It worked perfectly.

However, It isn't clear to me how to run the app with a custom environment. Let´s suppose I have a custom configuration file called "`environment.testing.ts`", how would you start / build the app from command line with that configuration?

Thanks!

**Comment by richardshergold** [comment]
I'm a little unsure of this too.  The Readme file mentions Custom environments - how do we add one?

**Comment by gshigeto** [comment]
Sorry I haven't gotten back to you on this one!

If more than `dev` and `prod` environments are wanted, there are a few things you will need to do.

1. Change your `optimization.config.js` and `webpack.config.js` `IONIC_ENV` variable to be something else. For example:
```javascript
'./src/environments/environment' + (process.env.MY_ENV === 'prod' ? '' : '.' + process.env.MY_ENV) + '.ts'
```
2. Add to your `package.json` another run script and name it whatever you would like
```json
"serve:testing": "MY_ENV=testing ionic-app-scripts serve"
```
3. Create your testing file `src/environments/environment.testing.ts`. This should be whatever you set your `MY_ENV` to.
4. Finally, run the script by using the name you used for your script in `package.json`
```bash
$ npm run serve:testing
```

**Comment by sapnagroup** [comment]
How do I run it for android and ios build?
