### ISSUE TITLE
How to use with Unit testing with Karma

### ISSUE THREAD

**Issue by inggil2407** [gshigeto/ionic-environment-variables#20]
I want to create unit testing but,  always get  "Uncaught Error: Cannot find module "@app/env""

**Comment by srjovanovic** [comment]
When I try to start karma unit testing, console shows errors: 
**Module not found: Error: Can't resolve  '@ app/env' in**...

P.S. Compiling and building works as it should (ionic serve, ionic build cordova, ionic cordova compile, ...).

**Comment by amtb** [comment]
Hi,

You need to tell webpack where to find (resolve) the `app/env` files...
I guess you have a `webpack.test.js` somewhere, if so, update the `resolve` block to look like this.

```
resolve: {
    alias: {
      '@app/env': path.resolve(environmentPath('dev'))
    },
    extensions: ['.ts', '.js']
  },
... 
```
Define your `environmentPath` function to return the path to your env config as in the README of the project. You can even extract it into a `env-helper.js` file outside of the webpack configs to avoid code duplication, and require your helper.

Hope it helps ;)

**Comment by srjovanovic** [comment]
Thank you very much!




Srdačan pozdrav,

*Srđan Jovanović*  |*  Developer Manager*
Emisia Consulting, Kragujevac, Serbia

**Comment by gshigeto** [comment]
I am going to close this as it seems to be resolved. Thanks!

**Comment by GFoley83** [comment]
@gshigeto This info should probably be added to the README as it's likely the majority of people will be using unit tests and this needs to be inplace in order to make them work.

**Comment by wilfredonoyola** [comment]
Hi @amtb , Could you share the example code? Thanks

**Comment by jhonycage** [comment]
Thanks god I found this, really...
