### ISSUE TITLE
Cannot find module '@app/env'.

### ISSUE THREAD

**Issue by wiadev** [gshigeto/ionic-environment-variables#21]
I've followed your steps but got the error `can't find a module`.

I've kept the config.dev.ts and config.prod.ts under ./config.
tsconfig.json
```
"baseUrl":  "./config",
    "paths": {
      "@app/env": ["config"]
    },
```
webpack.config.js
```
var path = require('path');
var useDefaultConfig = require('@ionic/app-scripts/config/webpack.config.js');
module.exports = function () {
    useDefaultConfig[process.env.IONIC_ENV].resolve.alias = {
        "@app/env": path.resolve(__dirname + '/config.' + process.env.IONIC_ENV + '.ts'),
    };
    return useDefaultConfig;
};
```

These are the same as you mentioned in README but still can't find a module.

Ionic v3.9.3

**Comment by Robinyo** [comment]
See:
- https://robferguson.org/blog/2017/11/22/working-with-typescript-webpack-and-ionic-3/
- https://github.com/Robinyo/ionic-angular-schematics
- https://robferguson.org/blog/2017/12/31/the-future-of-the-ionic-cli/

**Comment by enolcasielles** [comment]
Have you put `baseUrl` and `paths` inside `compilerOptions` object in tsconfig.json file? I had same error and this was the reason.

**Comment by wiadev** [comment]
@enolcasielles yes, I did.

```
"baseUrl":  "./config",
    "paths": {
      "@app/env": ["config"]
    },
```

I've followed the example in readme precisely and it worked but not sure why the above case is not working.

**Comment by enolcasielles** [comment]
Could be because you are indexing file from root directory instead config folder? Maybe you should change by:

`"@app/env": path.resolve(__dirname + 'config/config.' + process.env.IONIC_ENV + '.ts'),`

**Comment by wiadev** [comment]
@enolcasielles Thanks

**Comment by aronAtWex** [comment]
Out of the blue I'm getting the same problem.  Google lead me here.  

Created a new thread  
https://github.com/gshigeto/ionic-environment-variables/issues/39

**Comment by 0x14Rp** [comment]
> Could be because you are indexing file from root directory instead config folder? Maybe you should change by:
> 
> `"@app/env": path.resolve(__dirname + 'config/config.' + process.env.IONIC_ENV + '.ts'),`

this solution is not working?i am looking for something so i need to change environments when doing the build
