### ISSUE TITLE
Custom environment other than IONIC_ENV, is not recognized as an internal or external command

### ISSUE THREAD

**Issue by mastakillahBlitzar** [gshigeto/ionic-environment-variables#25]
when trying to change IONIC_ENV to BV_ENV, throws error 
`BV_ENV is not recognized as an internal or external command`

is there any other place where I have to declare this variable?

**Comment by AndrWeisR** [comment]
If you are on Windows, use a command like this in your package.json:

`"build:DEV": "set BV_ENV=DEV&& ionic-app-scripts build"`

Note there is no space between DEV and &&.

**Comment by anacesponda** [comment]
@AndrWeisR Thanks! It helped me
