### ISSUE TITLE
Cannot find module "@app/env" when trying to do unit tests

### ISSUE THREAD

**Issue by racedale** [gshigeto/ionic-environment-variables#6]
How is this supposed to resolve when testing?

**Comment by gshigeto** [comment]
Do you have an example of your testing framework? Are you using the ionic team unit testing example?

**Comment by racedale** [comment]
Yes using the ionic team unit testing example.  I actually just got this running by adding this `alias` section
```
resolve: {
    extensions: ['.ts', '.js'],
    alias: {
      "@app/env": root('../src/environments/environment.prod.ts')
    }
  },
``` 
to their `webpack.test.js` file.  

Can you add something to the documentation for future people, or maybe how to do it dynamically? In my case, I only want the production file for testing so that it doesn't send errors to Rollbar.

**Comment by Robinyo** [comment]
Hi,

The Ionic Unit Testing example isn't suitable for Production use. 

Take a look at this repo: https://github.com/lathonez/clicker
And, the associated blog post: http://lathonez.com/2017/ionic-2-unit-testing/

I've used Gavin's ENV approach and Angular's CLI for Unit and E2E Testing: https://github.com/ato-team/aus-id/

Cheers
Rob

**Comment by gshigeto** [comment]
Thank you, Rob! Dale, I am going to close this issue. Take a look at Rob's repo if you have any questions.

Thanks, guys!

**Comment by wilfredonoyola** [comment]
Hi! @Robinyo The links does not work
